services:
  server:
    build:
      context: .
      target: final
    ports:
      - "5000:8080" 
    depends_on:
      sqlserver:
        condition: service_healthy 
      redis:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ApiDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379,password=atara57769

  sqlserver:
    image: rapidfort/microsoft-sql-server-2019-ib:latest
    container_name: webapishop-ai-sqlserver-1
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck: 
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: redis-server --requirepass atara57769
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  sqlserver_data: